### ISSUE TITLE
Remove sidenav-animation on home page [JS]

### ISSUE THREAD

**Issue by pathob** [liotio/liotio.github.io#3]
When the map for the hover-effects on the graphic on the home page is active, there is an "slide-in" animation for the side navigation.

Possibly this has to do with the script that ensures that the map is resized together with the image.

**Comment by Lausi95** [comment]
Can't reproduce this bug on my own. How does this exactly happen?

**Comment by pathob** [comment]
Seems to occur only in firefox is somehow related to the map of the graphic on the home page.

But this is not so important and should be deferred for the moment.

**Comment by Lausi95** [comment]
fixed (removed) sidenav animation on home page
