### ISSUE TITLE
Auto-generate anchors for h2-elements [JS] 

### ISSUE THREAD

**Issue by pathob** [liotio/liotio.github.io#4]
It should be possible to jump directly so a specific section of a page. Therefore, it would be helpful to have auto-generated anchors for all h2-elements.

Maybe http://renaysha.me/anchorific-js/ can be used.

**Comment by Lausi95** [comment]
Each h2 container received now an anchor id.
The first h2 geits "#anchor-1", the second "#anchor-2" and so on
