### ISSUE TITLE
Images with fullscreen mode [JS+CSS]

### ISSUE THREAD

**Issue by pathob** [liotio/liotio.github.io#5]
I don't like the fact that the text is only slightly wider than the images on the ["Editor / IDE" page](http://www.liot.io/software/editor-ide/). Thus, the images should be a little bit less wide compared to the textwidth (maybe 80% or 90%) and it should be possible to open them in a nice fullscreen mode.

**Comment by pathob** [comment]
Example: https://www.quora.com/I-want-to-get-into-the-Internet-of-Things-IoT-industry-How-can-I-position-myself-to-start-there

**Comment by Lausi95** [comment]
Added fancybox to all images of the content area.
