### ISSUE TITLE
Named anchor

### ISSUE THREAD

**Issue by pathob** [liotio/liotio.github.io#7]
In order to preserve anchor-links when the content has changed (for example a new heading was inserted), the anchors should be based on the heading name instead of an ongoing number.

Spaces should be converted into -, other (non-alphanumeric) characters like &, \, ² etc. should only be removed.

Github shows an on-hover-link to the anchor when the cursor is over a heading, this would also be nice.

**Comment by Lausi95** [comment]
Added the Bootstrap-Scrollspy to match the current section with the Content-Navigation. Changed the design of it and added named anchors. Also headings received an mouseover anchor-link.
